const { d100 } = require('../dice');

const social_status_table = {
    "Acolyte": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 1, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 1, rivals: 1},
    },
    "Charlatan": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 1, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "City Watch": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Clan Crafter": {
        "Lords' Alliance": {allies: 0, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Cloistered Scholar": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Courtier": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 1, rivals: 1},
    },
    "Criminal": {
        "Lords' Alliance": {allies: 0, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 1, rivals: 0},
        "Underdark":  {allies: 1, rivals: 0},
    },
    "Entertainer": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 1},
        "Underdark":  {allies: 1, rivals: 0},
    },
    "Faction Agent": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 1, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 1},
        "Independent Realms":  {allies: 1, rivals: 1},
        "Underdark":  {allies: 1, rivals: 1},
    },
    "Far Traveler": {
        "Lords' Alliance": {allies: 0, rivals: 0},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Folk Hero": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 1, rivals: 0},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Guild Artisan": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Hermit": {
        "Lords' Alliance": {allies: 0, rivals: 0},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 1, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Inheritor": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 1},
        "Underdark":  {allies: 1, rivals: 1},
    },
    "Knight of the Order": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Mercenary Veteran": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 1},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Noble": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 1, rivals: 1},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 1, rivals: 1},
    },
    "Outlander": {
        "Lords' Alliance": {allies: 0, rivals: 0},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 1},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Sage": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Sailor": {
        "Lords' Alliance": {allies: 0, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 1, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Soldier": {
        "Lords' Alliance": {allies: 0, rivals: 1},
        "Dwarfholds of the North":  {allies: 1, rivals: 0},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Spy": {
        "Lords' Alliance": {allies: 0, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Urban Bounty Hunter": {
        "Lords' Alliance": {allies: 0, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 1},
        "Island Kingdoms":  {allies: 1, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Urchin": {
        "Lords' Alliance": {allies: 1, rivals: 0},
        "Dwarfholds of the North":  {allies: 0, rivals: 1},
        "Island Kingdoms":  {allies: 0, rivals: 1},
        "Independent Realms":  {allies: 0, rivals: 1},
        "Underdark":  {allies: 0, rivals: 1},
    },
    "Uthgardt Tribe Member": {
        "Lords' Alliance": {allies: 0, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 1, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
    "Waterdhavian Noble": {
        "Lords' Alliance": {allies: 1, rivals: 1},
        "Dwarfholds of the North":  {allies: 0, rivals: 0},
        "Island Kingdoms":  {allies: 0, rivals: 0},
        "Independent Realms":  {allies: 0, rivals: 0},
        "Underdark":  {allies: 0, rivals: 0},
    },
}

module.exports = {
    social_status_table
}